name: renovate

on:
  workflow_dispatch: # allows the workflow to be run manually when desired
  schedule: # runs this workflow at the scheduled time (UTC)
    - cron: '0 12 * * *'
  push: # runs this workflow when pushes to the main branch are made
    branches:
      - main

jobs:
  renovate:
    name: renovate
    runs-on: ubuntu-latest
    container: ghcr.io/renovatebot/renovate:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Run Renovate
        uses: https://github.com/renovatebot/github-action@v43.0.11
        with:
          docker-user: root
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: ${{ github.workspace }}/config.js
        env:
          RENOVATE_GITHUB_COM_TOKEN: ${{ secrets.RENOVATE_GITHUB_TOKEN }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
